<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>


<div class="toolbar-sorter sorter">
    <!-- sale button -->
    <div class="custom-salebtn" style="display:inline;">
    <label for="vehicle1">Show Sale Only</label>
    <input type="checkbox" id="customsale" name="sale1" value="Sale">
    </div>
    <!-- sale button -->
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
<!-- sale filter code -->
<script>
 require(['jquery'], function ($) {
    $( document ).ready(function() {
        let url_string=document.location.href;
        var url = new URL(url_string);
        var c = url.searchParams.get("csale");
        if(c==1){
            $('#customsale').prop('checked', true);
        }
    $('#customsale').change(function () {
        
        if(this.checked===true){
            if(document.location.href.includes('?')) {
                var url = document.location.href+"&csale=1";
            }else{
                var url = document.location.href+"?csale=1";
            }
            document.location = url;
        }else{
            let url_replace=window.location.href;
            url_replace=url_replace.replace('&csale=1','');
            url_replace=url_replace.replace('?csale=1','');
            url_replace=url_replace.replace('csale=1&','');
            document.location = url_replace;
        }
    });
});
});
</script>
<!-- sale filter code -->