<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB); ?>

<div id="brand-wacth">
     <div id="list-social">
        <a href="https://www.facebook.com/buywatchesonline.com.au/" target="_blank">
            <img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/casio/social1.png" height="24" width="24" class="">
        </a>
        <a href="http://instagram.com/buywatchesonline.com.au" target="_blank">
            <img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/casio/social2.png" height="24" width="24" class="">
        </a>
        <a href="https://www.youtube.com/channel/UCsZjmaQxS-BYmiUBhuhoG5g" target="_blank">
            <img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/casio/social3.png" height="24" width="24" class="last-social">
        </a>
    </div>
</div>