<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class=" box block block-dashboard-addresses">
    <div class="box-title">
        <strong><?= $block->escapeHtml(__('Address Book')) ?></strong>
        <a class="action edit" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>"><span><?= $block->escapeHtml(__('Manage Addresses')) ?></span></a>
    </div>
    <div class="box-content block-content">
        <div class="box box-billing-address">
                <h4><?= $block->escapeHtml(__('Default Billing Address')) ?></h4>
            <address>
                <?= $block->getPrimaryBillingAddressHtml() ?>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>" data-ui-id="default-billing-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                </div>
            </address>           
        </div>
        <div class="box box-shipping-address">
            <h4><?= $block->escapeHtml(__('Default Shipping Address')) ?></h4>
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                    <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                    </div> 
                </address>
 
        </div>
    </div>
</div>
