<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB); ?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<!-- custom -->
<div class="product-custom-afterpay">
    <div style="font-style: italic;line-height: 1.4;font-weight: 600;" class="afterpay-installments afterpay-installments-amount">
    or 4 interest free payments of $39.75
    <br>
    <img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/afterpay/images/ap-logo-152x31.png" style="width: 76px;vertical-align: middle;display: inline;
    ">
    <a href="#afterpay-what-is-modal" class="afterpay-what-is-modal-trigger">   Learn more </a>
    </div>
        <div class="widget-product-calc zipmoney-product-tagline"> 
            <span data-zm-widget="tagline" data-zm-info="true" class="zip-widget__wrapper zip-widget__wrapper--display-tagline">
                <div class="zip-widget zip-widget__tagline" title="Zip now, Pay later">
                    <span class="text">Zip it now, pay later</span>
                    <img class="logo" alt="Zip Payment" src="https://zip.co/static/assets/default/product-widget/img/zip-button-wht.svg">
                    <button class="zip-info-link" id="zip-info-link" title="Zip payment Information">
                        <span class="zip-learn-more">ⓘ</span>
                    </button>
                </div>
            </span> 
        </div>
    </div>
<!-- custom -->
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
