<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
?>

<div class="stipe-banner"><a href="https://www.buywatchesonline.com.au/firecheckout/"><img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/strippowered.png"></a></div>
<ul class="checkout-types">
     <li class="checkout-cart-button">
        <button type="button" title="Proceed to Checkout" class="button btn-proceed-checkout btn-checkout" onclick="window.location='https://www.buywatchesonline.com.au/firecheckout';">
            <span>
                <span>
                    <img class="lock-checkout" src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/lock.png">Pay Securely Now
                    </span>
                </span>
        </button>
    </li>
</ul>