<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <p>Get all the latest information on Events,<br>Sales and Offers. Sign up for newsletter today.</p>
            <div class="input-box">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <p class="label">Enter your e-mail Address</p>
                        <input name="email" type="email" id="newsletter"
                               title="Sign up for our newsletter" class="input-text required-entry validate-email"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
                <button class="button"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
        </div>
        </form>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
