<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB); ?>

<div id="brand-wacth">
     <div id="list-social">
        <a href="https://www.facebook.com/buywatchesonline.com.au/" target="_blank">
            <img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/casio/social1.png" height="24" width="24" class="">
        </a>
        <a href="http://instagram.com/buywatchesonline.com.au" target="_blank">
            <img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/casio/social2.png" height="24" width="24" class="">
        </a>
        <a href="https://www.youtube.com/channel/UCsZjmaQxS-BYmiUBhuhoG5g" target="_blank">
            <img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/casio/social3.png" height="24" width="24" class="last-social">
        </a>
    </div>
    <?php
$baby_catid= 1686;
$g_shock_catid= 1685;
$citizen_catid= 1656;
$cat_ids =  array();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$categories = $product->getCategoryIds(); /*will return category ids array*/
foreach($categories as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    $cat_ids[] = $cat->getId();
    }
    if (in_array($baby_catid, $cat_ids)) {//Baby G  ?>
        <p class="more-casio" id="baby-desktop"><a href="<?php echo $baseUrl;?>baby-g.html" title="More Casio Baby-G Watches">More Casio Baby-G Watches</a></p>
    
        <a class="baby-g" href="<?php echo $baseUrl;?>baby-g.html" title="More Casio Baby-G Watches"><img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatch/images/casio/babyg.jpg" alt="More Casio Baby-G Watches"/></a>
    
         <p class="more-casio" id="baby-mobile"><a href="<?php echo $baseUrl;?>baby-g.html" title="More Casio Baby-G Watches">More Casio Baby-G Watches</a></p>
      <?php }?>
      
      <?php if (in_array($g_shock_catid, $cat_ids)) {//G Shock  ?>
          <p class="more-casio" id="g-shock-desktop"><a href="<?php echo $baseUrl;?>g-shock.html" title="More Casio G Shock Watches">More Casio G Shock Watches</a></p>
    
          <a class="g-shock"  href="<?php echo $baseUrl;?>g-shock.html" title="More Casio G Shock Watches"><img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatch/images/casio/gshock.jpg" alt="More Casio G Shock Watches" /></a>
    
            <p class="more-casio" id="g-shock-mobile"><a href="<?php echo $baseUrl;?>g-shock.html" title="More Casio G Shock Watches">More Casio G Shock Watches</a></p>
      <?php }?>
      
      <?php if (in_array($citizen_catid, $cat_ids)) {//G Shock  ?>
          <p class="more-casio" id="citizen-desktop"><a href="<?php echo $baseUrl;?>citizen-watches.html" title="More Citizen Watches">More Citizen Watches</a></p>
    
          <a class="g-shock citizen-watches"  href="<?php echo $baseUrl;?>citizen-watches.html" title="More Citizen Watches"><img src="<?php echo $baseUrl;?>pub/media/smartwave/portowatch/images/casio/citizen-watches.jpg" alt="More Citizen Watches" /></a>
    
            <p class="more-casio" id="g-shock-mobile"><a href="<?php echo $baseUrl;?>citizen-watches.html" title="More Citizen Watches">More Citizen Watches</a></p>
      <?php }?>
</div>
