<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
    <?php if (($block->escapeHtmlAttr($_code) == "flatfee") || ($block->escapeHtmlAttr($_code) == "fee")) { 
        if(($_total->getValue() != "") && ($_total->getValue() > 0.00)) {
            ?>
            <tr class="<?= $block->escapeHtmlAttr($_code) ?> check">
                <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                    <?php if ($_total->getStrong()) : ?>
                        <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                    <?php else : ?>
                        <?= $block->escapeHtml($_total->getLabel()) ?>
                    <?php endif ?>
                </th>
                <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
                    <?php if ($_total->getStrong()) : ?>
                        <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                    <?php else : ?>
                        <?= /* @noEscape */ $block->formatValue($_total) ?>
                    <?php endif?>
                </td>
            </tr>
       <?php 
       }

    }
    if (($block->escapeHtmlAttr($_code) != "flatfee") && ($block->escapeHtmlAttr($_code) != "fee")) { ?>
        <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                <?php else : ?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php endif ?>
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                <?php else : ?>
                    <?= /* @noEscape */ $block->formatValue($_total) ?>
                <?php endif?>
            </td>
        </tr>
    <?php } ?>
    <?php endif; ?>
<?php endforeach?>
