<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB); ?>
<div class="partner-banner">
	<a href="https://www.buywatchesonline.com.au/official-casio-warranty/"><img class="partner-banner_img" src="<?php echo $baseUrl;?>pub/media/smartwave/portowatchau/images/casio.png" ></a>
</div>