<div class="std">
    <div class="bw-home-img-box">   
    
            
        <a href="https://www.buywatchesonline.com.au/latest-releases.html/?amp=1" title=""><amp-img alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img1.jpg" width="237" height="198" layout="responsive" class="bw-home-img i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built i-amphtml-layout" i-amphtml-layout="responsive" i-amphtml-auto-lightbox-visited=""><i-amphtml-sizer slot="i-amphtml-svc" style="padding-top: 83.5443%;"></i-amphtml-sizer><img decoding="async" alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img1.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content"></amp-img></a>
        <a href="https://www.buywatchesonline.com.au/official-casio-warranty/?amp=1" title=""><amp-img alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/about-banner.jpg" width="237" height="198" layout="responsive" class="bw-home-img i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built i-amphtml-layout" i-amphtml-layout="responsive" i-amphtml-auto-lightbox-visited=""><i-amphtml-sizer slot="i-amphtml-svc" style="padding-top: 83.5443%;"></i-amphtml-sizer><img decoding="async" alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/about-banner.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content"></amp-img></a>
        <a href="https://www.buywatchesonline.com.au/g-shock.html/?amp=1" title=""><amp-img alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img2.jpg" width="237" height="198" layout="responsive" class="bw-home-img i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built i-amphtml-layout" i-amphtml-layout="responsive" i-amphtml-auto-lightbox-visited=""><i-amphtml-sizer slot="i-amphtml-svc" style="padding-top: 83.5443%;"></i-amphtml-sizer><img decoding="async" alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img2.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content"></amp-img></a>
        <a href="https://www.buywatchesonline.com.au/clearance.html/?amp=1" title=""><amp-img alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img3.jpg" width="237" height="198" layout="responsive" class="bw-home-img i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built i-amphtml-layout" i-amphtml-layout="responsive" i-amphtml-auto-lightbox-visited=""><i-amphtml-sizer slot="i-amphtml-svc" style="padding-top: 83.5443%;"></i-amphtml-sizer><img decoding="async" alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img3.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content"></amp-img></a>
        <a href="https://www.buywatchesonline.com.au/baby-g.html/?amp=1" title=""><amp-img alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img5.jpg" width="237" height="198" layout="responsive" class="bw-home-img i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built i-amphtml-layout" i-amphtml-layout="responsive" i-amphtml-auto-lightbox-visited=""><i-amphtml-sizer slot="i-amphtml-svc" style="padding-top: 83.5443%;"></i-amphtml-sizer><img decoding="async" alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img5.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content"></amp-img></a>
        <a href="https://www.buywatchesonline.com.au/kids-teen-watches.html/?amp=1" title=""><amp-img alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img6.jpg" width="237" height="198" layout="responsive" class="bw-home-img i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built i-amphtml-layout" i-amphtml-layout="responsive" i-amphtml-auto-lightbox-visited=""><i-amphtml-sizer slot="i-amphtml-svc" style="padding-top: 83.5443%;"></i-amphtml-sizer><img decoding="async" alt="" src="https://www.buywatchesonline.com.au/skin/frontend/smartwave/portowatchau/images/plumrocket/pramp/img6.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content"></amp-img></a>   
    </div>
    <div>
        <div class="tvcontainer">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="filter-title"><span class="content"><strong>Featured Products </strong></span></h2>
                    <div id="featured_product" class="owl-top-narrow">
                            <div class="filter-products">
    {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="Featured Product Mobile" show_pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid_mobile.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`featured`,`operator`:`==`,`value`:`1`^]^]"}}
                    
        </div>
     
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="tvcontainer">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="filter-title highlighted-title"><span class="content"><strong>WELCOME TO BUY WATCHES ONLINE</strong></span></h2>
                    <div class="content">
                        <p>Buying a watch online can be a difficult process, but it doesn’t have to be. The hard part is not in the actual buying, but the after sales service (or lack there of), and the peace of mind that you would normally associate with purchasing the same watch in store. We have asked ourselves this question – “How can we make the process of purchasing a watch online as good as, and even better than going to a retail store?”  What are the things that our customers really care about and how can we exceed their expectations. </p>
                        <p>Well we have come up with the below: </p>
                        <p>We offer Same Day Express Shipping (with insurance and online tracking of course). Order before 2pm and your item will be sent the very same business day.</p>
                        <p>Free and Easy returns policy (365 day money back guarantee). Yes, you’ll have a full year decide whether you want to keep your item. If you change your mind – No problem! Simply return it to us in as received condition for a full refund. </p>
                        <p>Full Warranty and old school customer service (the way it should be). Every item we sell is fully covered by warranty. Our staff are always happy to help. We won’t let you down – Promise! </p>
                        <p>We have a Great Range – Casio G Shock, Casio Baby G, Edifice, Citizen, Seiko, Michael Kors…
                            So take this advice and don’t think twice, want to buy a watch online at the right price? Be swift, be picky, be clever, be smart – so go on, click Add To Cart…
                            See, we can even rhyme!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>